SELECT
    T.TRA_DATE TRANS_DATE,
    T.TRA_SEQ1 TRANS_SEQ1,
    T.TRA_SEQ2 TRANS_SEQ2,
    B.DES_ENG BRANCH,
    T.CUS_NUM CUSTOMER_NUMBER,
    A.NAME_LINE1 CUSTOMER_NAME,
    C.DES_ENG CURRENCY,
    C_A.DES_ENG LEDGER_CODE,
    T.SUB_ACCT_CODE,
    /*DIS_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 11 AND T.DIS_CODE = TT.TAB_ENT) DIS_CODE,
    T.TRA_AMT TRANS_AMT,
    /*DEB_CRE_IND*/  CASE WHEN T.DEB_CRE_IND  = 1 THEN 'DEBIT' WHEN T.DEB_CRE_IND  = 2 THEN 'CREDIT' END TRANS_TYPE ,
    T.CRNT_BAL CURRENT_BAL ,
    /*EXPL_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 60 AND T.EXPL_CODE = TT.TAB_ENT) CHANNEL,
    T.ORIGT_BRA_CODE ORIGIN_BRANCH,
    /*CITY_LOC_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 190 AND T.CITY_LOC_CODE = TT.TAB_ENT) CITY,
    REMARKS
FROM TRANSACT T
JOIN BRANCH B
ON B.BRA_CODE = T.BRA_CODE
JOIN ADDRESS A
ON A.BRA_CODE = T.BRA_CODE AND  A.CUS_NUM = T.CUS_NUM AND  A.CUR_CODE  = T.CUR_CODE AND A.LED_CODE  = T.LED_CODE AND A.SUB_ACCT_CODE  = T.LED_CODE
JOIN CURRENCY C
ON C.CUR_CODE = T.CUR_CODE
JOIN CHRT_ACT C_A
ON C_A.LED_TYPE = T.LED_CODE
;


SELECT 
    T.TRA_DATE TRANS_DATE, 
    B.DES_ENG BRANCH, 
    A.NAME_LINE1 CUSTOMER_NAME, 
    C.DES_ENG CURRENCY, 
    C_A.DES_ENG LEDGER, 
    T.SUB_ACCT_CODE, 
    /*T.EXT_INT_FLAG*/  CASE WHEN T.EXT_INT_FLAG = 0 THEN 'External Only' WHEN T.EXT_INT_FLAG = 1 THEN 'Internal and External' END TRANS_INDICATOR,
    /*T.DEP_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 20 AND T.DEP_CODE = TT.TAB_ENT) DEPARTMENT,
    /*DIS_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 11 AND T.DIS_CODE = TT.TAB_ENT) DIS_CODE , 
    T.TRA_AMT TRANS_AMT, 
    /*DEB_CRE_IND*/  CASE WHEN T.DEB_CRE_IND  = 1 THEN 'DEBIT' WHEN T.DEB_CRE_IND  = 2 THEN 'CREDIT' END TRANS_TYPE , 
    T.CRNT_BAL CURRENT_BAL, 
    /*EXPL_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 60 AND T.EXPL_CODE = TT.TAB_ENT) CHANNEL,
    T.ORIGT_BRA_CODE ORIGIN_BRANCH, 
    /*CITY_LOC_CODE*/ (SELECT DES_ENG FROM TEXT_TAB TT WHERE TAB_ID = 190 AND T.CITY_LOC_CODE = TT.TAB_ENT) CITY 
FROM TRANSACT T
JOIN BRANCH B
ON B.BRA_CODE = T.BRA_CODE
JOIN ADDRESS A
ON A.BRA_CODE = T.BRA_CODE AND  A.CUS_NUM = T.CUS_NUM AND  A.CUR_CODE  = T.CUR_CODE AND A.LED_CODE  = T.LED_CODE AND A.SUB_ACCT_CODE  = T.LED_CODE
JOIN CURRENCY C
ON C.CUR_CODE = T.CUR_CODE
JOIN CHRT_ACT C_A
ON C_A.LED_TYPE = T.LED_CODE;